language: python
python:
    - "3.6"
cache: pip
sudo: false
install:
    - pip install sphinx sphinx_rtd_theme
script:
    - make html
    - touch build/html/.nojekyll
deploy:
    provider: pages
    skip_cleanup: try
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: source
    target_branch: master
    local_dir: build/html
